"""tables for admin

Revision ID: 2b80bdf48d6b
Revises: aeb5036cfae5
Create Date: 2026-09-13 11:16:11.801908+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import UUID
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b80bdf48d6b'
down_revision: Union[str, Sequence[str], None] = 'aeb5036cfae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "system_prompts",
        sa.Column(
            "id",
            UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("FALSE"),
        ),
        sa.Column(
            "traffic_pct",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column("notes", sa.Text(), nullable=True),
    )

    # --- chat_messages.prompt_id FK --------------------------------------
    op.create_foreign_key(
        "fk_chat_messages_prompt_id",
        source_table="chat_messages",
        referent_table="system_prompts",
        local_cols=["prompt_id"],
        remote_cols=["id"],
        ondelete="SET NULL",
    )

    op.add_column('chats', sa.Column('handoff_status', sa.String(), server_default='active', nullable=False))
    # ### end Alembic commands ###
# --- rate_limits ------------------------------------------------------
    op.create_table(
        "rate_limits",
        sa.Column("owner_external_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("bucket", sa.Text(), nullable=False),
        sa.Column(
            "count",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.PrimaryKeyConstraint(
            "owner_external_id",
            "kind",
            "bucket",
            name="pk_rate_limits",
        ),
    )
    op.create_index(
        "idx_rate_limits_bucket",
        "rate_limits",
        ["bucket"],
    )
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'handoff_status')
    # ### end Alembic commands ###

    op.drop_index("idx_rate_limits_bucket", table_name="rate_limits")
    op.drop_table("rate_limits")
    op.drop_column("chats", "handoff_status")
    op.drop_constraint(
        "fk_chat_messages_prompt_id", "chat_messages", type_="foreignkey"
    )
    op.drop_table("system_prompts")
