---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	call_model(call_model)
	execute_tool(execute_tool)
	prepare_synonyms(prepare_synonyms)
	approve_and_add(approve_and_add)
	force_finish(force_finish)
	__end__([<p>__end__</p>]):::last
	__start__ --> call_model;
	approve_and_add --> call_model;
	call_model -.-> execute_tool;
	call_model -.-> force_finish;
	call_model -.-> prepare_synonyms;
	execute_tool --> call_model;
	prepare_synonyms --> approve_and_add;
	force_finish --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
